In [7]:
import numpy as np
from collections import Counter

def find_duplicate_rows(X):
    Z = X
    # 将数组中的每一行表示为元组，并将这些元组存储在列表中
    row_tuples = [tuple(row) for row in Z]

    # 使用Python的collections.Counter来计算元组的出现次数
    row_counts = Counter(row_tuples)

    # 初始化总的重复次数
    total_duplicate_count = 0

    # 创建一个集合来存储已经计数过的行
    counted_rows = set()

    # 打印重复行的行号（索引）和它们的重复次数，并计算总的重复次数
    for index, row in enumerate(Z):
        row_tuple = tuple(row)
        if row_tuple not in counted_rows:
            count = row_counts[row_tuple]
            if count > 1:
                print(f"行 {index + 1} 重复了 {count} 次")
                total_duplicate_count += count
            counted_rows.add(row_tuple)  # 将该行添加到已计数的行集合中

    # 打印总的重复次数
    print(f"总的重复次数为: {total_duplicate_count}")

    # 初始化总的不同重复行数
    total_unique_duplicate_count = 0

    # 创建一个集合来存储已经计数过的行
    counted_rows = set()

    # 计算不同的重复行数
    for row_tuple, count in row_counts.items():
        if count > 1:
            total_unique_duplicate_count += 1
            counted_rows.add(row_tuple)

    # 打印总的不同重复行数
    print(f"总的不同重复行数为: {total_unique_duplicate_count}")

In [2]:
import pandas as pd

file_path = 'data.s1.xlsx'  
df = pd.read_excel(file_path, index_col=0, header=0)

# 提取第10列到倒数第四列的成分特征数据
composition_data = df.iloc[:, 9:-3]

Index(['C (mass%)', 'Si (mass%)', 'Mn (mass%)', 'P (mass%)', 'S (mass%)',
       'Ni (mass%)', 'Cr (mass%)', 'Mo (mass%)', 'Cu (mass%)', 'W (mass%)',
       'Co (mass%)', 'Al (mass%)', 'N (mass%)', 'Nb+Ta (mass%)', 'B (mass%)',
       'V (mass%)', 'Ti (mass%)', 'Fe (mass%)', 'Zr (mass%)', 'Re (mass%)',
       'Y (mass%)', 'Hf (mass%)'],
      dtype='object')

In [3]:
composition_data.describe()

,C (mass%),Si (mass%),Mn (mass%),P (mass%),S (mass%),Ni (mass%),Cr (mass%),Mo (mass%),Cu (mass%),W (mass%),...,N (mass%),Nb+Ta (mass%),B (mass%),V (mass%),Ti (mass%),Fe (mass%),Zr (mass%),Re (mass%),Y (mass%),Hf (mass%)
count,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000,...,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000
mean,0.094954,0.200040,0.400736,0.004373,0.004694,50.704973,13.753692,1.740112,0.016680,2.919203,...,0.014855,3.084914,0.007809,0.029163,1.413028,9.983047,0.001009,1.043400,0.003268,0.093639
std,0.111987,0.271114,0.610992,0.005504,0.005795,20.340134,6.072540,1.572555,0.022517,3.085502,...,0.033453,3.329694,0.012062,0.089950,1.297598,16.721397,0.006277,1.845655,0.009519,0.435336
min,0.000000,0.000000,0.000000,0.000000,0.000000,10.350000,0.600000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.040000,0.000000,0.000000,0.000000,0.000000,26.440000,8.000000,0.120000,0.000000,0.000000,...,0.000000,0.000000,0.000100,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.060000,0.030000,0.050000,0.002000,0.002000,60.100000,15.100000,1.400000,0.010000,2.540000,...,0.003000,1.000000,0.004300,0.000000,1.500000,0.240000,0.000000,0.000000,0.000000,0.000000
75%,0.100000,0.470000,0.610000,0.007000,0.008000,65.281000,19.230000,3.630000,0.020000,5.590000,...,0.007300,6.000000,0.008000,0.000000,2.570000,8.670000,0.000000,2.000000,0.000000,0.150000
max,0.430000,0.860000,1.910000,0.019000,0.023000,77.260000,25.430000,4.400000,0.080000,18.600000,...,0.160000,12.000000,0.050000,0.320000,5.000000,53.176600,0.040000,7.500000,0.050000,5.600000

In [4]:
x_data = df.iloc[:, :9].join(df.iloc[:, -3:-1])
y_data = df.iloc[:, -1]

In [6]:
x_data.describe()

,Solution treatment time (h),Solution treatment temperature (℃),Solution cooling way,Aging treatment time (h),Aging treatment temperature (℃),Aging cooling way,2nd aging treatment time (h),2nd aging treatment temperature (℃),2nd aging cooling way,Test temperature (℃),Test stress (MPa)
count,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000
mean,2.600266,1176.597610,1.378486,11.100930,934.103586,0.849934,11.410359,507.624170,0.257636,847.618858,253.861301
std,1.212019,106.675781,1.369856,8.675467,148.732195,0.966213,9.156601,401.120059,0.437623,201.868169,173.615081
min,0.500000,899.000000,0.000000,1.000000,704.000000,0.000000,0.000000,0.000000,0.000000,204.000000,10.000000
25%,2.000000,1149.000000,0.000000,4.000000,815.000000,0.000000,0.000000,0.000000,0.000000,700.000000,137.000000
50%,2.000000,1180.000000,1.000000,4.000000,870.000000,1.000000,16.000000,705.000000,0.000000,850.000000,216.000000
75%,4.000000,1280.000000,3.000000,24.000000,1080.000000,1.000000,20.000000,870.000000,1.000000,982.000000,350.000000
max,5.000000,1348.000000,4.000000,24.000000,1145.000000,4.000000,32.000000,899.000000,1.000000,1800.000000,800.000000

In [26]:
find_duplicate_rows(x_data)
x_data.shape

总的重复次数为: 0
总的不同重复行数为: 0

(753, 11)

In [10]:
new_data = df.iloc[:, :9].join(df.iloc[:, -3:])

new_data.describe()

,Solution treatment time (h),Solution treatment temperature (℃),Solution cooling way,Aging treatment time (h),Aging treatment temperature (℃),Aging cooling way,2nd aging treatment time (h),2nd aging treatment temperature (℃),2nd aging cooling way,Test temperature (℃),Test stress (MPa),Creep rupture life (h)
count,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000,753.000000
mean,2.600266,1176.597610,1.378486,11.100930,934.103586,0.849934,11.410359,507.624170,0.257636,847.618858,253.861301,5467.765737
std,1.212019,106.675781,1.369856,8.675467,148.732195,0.966213,9.156601,401.120059,0.437623,201.868169,173.615081,15470.033561
min,0.500000,899.000000,0.000000,1.000000,704.000000,0.000000,0.000000,0.000000,0.000000,204.000000,10.000000,1.200000
25%,2.000000,1149.000000,0.000000,4.000000,815.000000,0.000000,0.000000,0.000000,0.000000,700.000000,137.000000,104.100000
50%,2.000000,1180.000000,1.000000,4.000000,870.000000,1.000000,16.000000,705.000000,0.000000,850.000000,216.000000,491.000000
75%,4.000000,1280.000000,3.000000,24.000000,1080.000000,1.000000,20.000000,870.000000,1.000000,982.000000,350.000000,3208.800000
max,5.000000,1348.000000,4.000000,24.000000,1145.000000,4.000000,32.000000,899.000000,1.000000,1800.000000,800.000000,151536.000000

In [11]:
fe_data = new_data.iloc[:72, :]
oth_data = new_data.iloc[72:173, :]
co_data = new_data.iloc[173:211, :]
ni_data = new_data.iloc[211:753, :]

In [12]:
fe_data.to_excel('Fe.xlsx', index=False)
oth_data.to_excel('others.xlsx', index=False)
co_data.to_excel('Co.xlsx', index=False)
ni_data.to_excel('Ni.xlsx', index=False)

# 钛合金数据处理

In [21]:

file_path_2 = 'data.s2.xlsx'    # y 记得加负号 ，如果需要原始值，需要反log回去
df_2 = pd.read_excel(file_path_2)
ti_data = df_2.iloc[:, 1:9].join(df_2.iloc[:, -3:])

In [22]:
ti_data.describe()

,Solution treatment time (h),Solution treatment temperature (℃),Solution cooling way,Aging treatment time (h),Aging treatment temperature (℃),Aging cooling way,2nd aging treatment time (h),2nd aging treatment temperature (℃),Test temperature (℃),Test stress (MPa),Creep rupture life (h)
count,88.000000,88.000000,88.000000,88.000000,88.000000,88.000000,88.000000,88.000000,88.000000,88.000000,88.000000
mean,0.801136,685.478977,0.738636,2.772727,467.013068,0.670455,1.136364,13.863636,603.409091,283.863636,299.009197
std,0.927051,484.041246,0.634167,8.444174,330.428219,0.472742,7.494338,91.430921,47.673129,90.266805,796.870927
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,475.000000,97.000000,0.001570
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,600.000000,220.000000,20.500000
50%,0.000000,1010.000000,1.000000,0.000000,699.850000,1.000000,0.000000,0.000000,600.000000,291.000000,53.500000
75%,2.000000,1021.250000,1.000000,2.000000,700.000000,1.000000,0.000000,0.000000,650.000000,331.000000,203.500000
max,2.000000,1080.000000,3.000000,50.000000,770.000000,1.000000,50.000000,610.000000,675.000000,550.000000,4770.000000

In [27]:
find_duplicate_rows(ti_data)
ti_data.shape

总的重复次数为: 0
总的不同重复行数为: 0

(88, 11)

In [28]:
ti_data.to_excel('Ti.xlsx', index=False)